name: cppcheck-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    artifacts:
        paths:
        - cppcheck-report.txt
    expire_in: 1 week
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt install -y parallel

    - name: Run cppcheck locally
      run: |
        cppcheck --enable=all --std=c++11 --language=c++ --output-file=cppcheck-report.txt .

