name: cppcheck-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt install -y cppcheck

    - name: Run cppcheck locally
      run: |
        cppcheck --enable=all --std=c++14 --language=c++ --suppress=unusedFunction --suppress=toomanyconfigs --suppress=unmatchedSuppression --output-file=cppcheck-report.txt --error-exitcode=13 .
    - name: Archive production artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
          name: cppcheck-report
          path: |
            cppcheck-report.txt

